name: Build custom Docker Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches:
      - master
    paths:
      - apps/**
jobs:
  push:
    name: "docker:apps_${{ matrix.app }}"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        app:
          - boypetter
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ARM64
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # v3.0.0
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6 # v5.0.0
        with:
          context: ./apps/${{ matrix.app }}
          file: ./apps/${{ matrix.app }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/peterstrick/apps:${{ matrix.app }}
